spring:
  application:
    name: transfer-order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/transfer?serverTimezone=CST&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123456



dubbo:
  registry:
    address: zookeeper://47.94.194.165:2181;zookeeper://47.94.194.165:2182;zookeeper://47.94.194.165:2183

  config-center:
    timeout: 6000
#


# 自定义参数消息

mq:
  task:
    match:
      topic: taskMatchTopic
      tag: task_match

    result:
      topic: taskMatchResult


  rocketmq:
    name-server: 47.94.194.165:9876

    consumer:
      group: task_match_group
      consumeThreadMin: 5
      consumeThreadMax: 10

    producer:
      group: matchResultgroup
      send-message:
          timeout: 50000


featuremake:
  version: 1.0.0
  url: dubbo://47.94.194.165:20880

featuresearch:
  version: 1.0.0
  url: dubbo://47.94.194.165:20881